Repository apify/actor-templates, pull requests merged in 2023-06, with the labels that each got.

#154 feat: adding readme suffixes to the manifest
  src/index.js
  templates/console_readme_suffix.md
  templates/local_readme_suffix.md
Labels: t-web

#156 feat: manifest suffix urls
  src/index.js
  templates/manifest.json
Labels: adhoc, t-web

#146 feat: Reverting dynamic READMEs generation with template structure
  package.json
  templates/js-crawlee-cheerio/README.md
  templates/js-crawlee-playwright-chrome/README.md
  templates/js-crawlee-puppeteer-chrome/README.md
  templates/js-cypress/README.md
  templates/js-empty/README.md
  templates/js-start/README.md
  templates/python-beautifulsoup/README.md
  templates/python-playwright/README.md
  templates/python-scrapy/README.md
  templates/python-selenium/README.md
  templates/python-start/README.md
  templates/readmeTemplate.mjs
  templates/readmeTemplate.mustache
  templates/ts-crawlee-cheerio/README.md
  templates/ts-crawlee-playwright-chrome/README.md
  templates/ts-crawlee-puppeteer-chrome/README.md
  templates/ts-playwright-test-runner/README.md
  templates/ts-start/README.md
Labels: t-web

#157 feat: remove documentation reference and writting readmes section
  templates/js-bootstrap-cheerio-crawler/README.md
  templates/js-crawlee-cheerio/README.md
  templates/js-crawlee-playwright-chrome/README.md
  templates/js-crawlee-puppeteer-chrome/README.md
  templates/js-empty/README.md
  templates/js-start/README.md
  templates/python-beautifulsoup/README.md
  templates/python-playwright/README.md
  templates/python-scrapy/README.md
  templates/python-selenium/README.md
  templates/python-start/README.md
  templates/ts-bootstrap-cheerio-crawler/README.md
  templates/ts-crawlee-cheerio/README.md
  templates/ts-crawlee-playwright-chrome/README.md
  templates/ts-crawlee-puppeteer-chrome/README.md
  templates/ts-start/README.md
Labels: adhoc, t-web

#149 feat: Added `ts-empty` template
  templates/manifest.json
  templates/ts-empty/.actor/Dockerfile
  templates/ts-empty/.actor/actor.json
  templates/ts-empty/.dockerignore
  templates/ts-empty/.gitignore
  templates/ts-empty/README.md
  templates/ts-empty/package.json
  templates/ts-empty/src/main.ts
  templates/ts-empty/tsconfig.json
Labels: t-web

#152 feat(ts-scrape-single-page): starter template for scraping a single page
  templates/manifest.json
  templates/ts-scrape-single-page/.actor/Dockerfile
  templates/ts-scrape-single-page/.actor/actor.json
  templates/ts-scrape-single-page/.actor/input_schema.json
  templates/ts-scrape-single-page/.dockerignore
  templates/ts-scrape-single-page/.gitingore
  templates/ts-scrape-single-page/README.md
  templates/ts-scrape-single-page/main.ts
  templates/ts-scrape-single-page/package.json
  templates/ts-scrape-single-page/src/main.ts
  templates/ts-scrape-single-page/storage/key_value_stores/default/INPUT.json
  templates/ts-scrape-single-page/tsconfig.json
  templates/ts-start/.actor/actor.json
  templates/ts-start/.actor/input_schema.json
  templates/ts-start/README.md
  templates/ts-start/src/main.ts
Labels: t-web

#148 feat: Simplified the`js-empty` template
  README.md
  dist/templates/js-empty.zip
  templates/js-empty/.actor/Dockerfile
  templates/js-empty/.actor/actor.json
  templates/js-empty/.actor/input_schema.json
  templates/js-empty/README.md
  templates/js-empty/main.js
  templates/js-empty/package.json
  templates/js-empty/src/main.js
  templates/manifest.json
Labels: t-web

#150 feat: Added `js-scrape-single-page` template
  templates/js-start/.actor/Dockerfile
  templates/js-start/.actor/actor.json
  templates/js-start/.actor/input_schema.json
  templates/js-start/.gitignore
  templates/js-start/README.md
  templates/js-start/package.json
  templates/js-start/src/main.js
  templates/manifest.json
Labels: t-web

#159 feat: rename readme titles
  templates/js-bootstrap-cheerio-crawler/README.md
  templates/js-crawlee-cheerio/README.md
  templates/js-crawlee-playwright-chrome/README.md
  templates/js-crawlee-puppeteer-chrome/README.md
  templates/js-cypress/README.md
  templates/js-empty/README.md
  templates/js-start/README.md
  templates/python-beautifulsoup/README.md
  templates/python-playwright/README.md
  templates/python-scrapy/README.md
  templates/python-selenium/README.md
  templates/python-start/README.md
  templates/ts-bootstrap-cheerio-crawler/README.md
  templates/ts-crawlee-cheerio/README.md
  templates/ts-crawlee-playwright-chrome/README.md
  templates/ts-crawlee-puppeteer-chrome/README.md
  templates/ts-playwright-test-runner/README.md
  templates/ts-start/README.md
Labels: adhoc, t-web

#161 feat: add use cases to manifest
  templates/manifest.json
Labels: t-web, tested

#162 fix: new starter template fixes
  dist/templates/ts-empty.zip
  dist/templates/ts-start.zip
  templates/ts-start/main.ts
Labels: bug, adhoc, t-web

#163 chore: Apply EditorConfig rules everywhere
  package-lock.json
  package.json
  templates/.eslintrc.json
  templates/js-crawlee-playwright-chrome/.gitignore
  templates/js-cypress/.actor/actor.json
  templates/js-cypress/package.json
  templates/js-start/.actor/input_schema.json
  templates/js-start/README.md
  templates/python-beautifulsoup/.actor/actor.json
  templates/python-empty/.actor/actor.json
  templates/python-empty/requirements.txt
  templates/python-scrapy/.actor/actor.json
  templates/python-selenium/.actor/actor.json
  templates/python-start/.actor/actor.json
  templates/python-start/.actor/input_schema.json
  templates/python-start/README.md
  templates/ts-crawlee-cheerio/.actor/actor.json
  templates/ts-empty/.actor/actor.json
  templates/ts-playwright-test-runner/.actor/actor.json
  templates/ts-playwright-test-runner/.actor/input_schema.json
  templates/ts-playwright-test-runner/.actor/output_schema.json
  templates/ts-playwright-test-runner/.gitignore
  templates/ts-playwright-test-runner/package.json
  templates/ts-playwright-test-runner/playwright.config.ts
  templates/ts-playwright-test-runner/src/main.ts
  templates/ts-playwright-test-runner/src/runCodegen.ts
  templates/ts-playwright-test-runner/src/transform.ts
  templates/ts-playwright-test-runner/tests/first.spec.ts
  templates/ts-playwright-test-runner/tests/second.spec.ts
  tsconfig.eslint.json
Labels: t-platform, adhoc, tested
