Repository apify/actor-templates, pull requests merged in 2023-04, with the labels that each got.

#139 feat(app): add showcase files to manifest.json
  templates/manifest.json
Labels: t-web

#141 Increase memory for Python templates that use browsers
  templates/manifest.json
Labels: t-platform, adhoc

#143 fix: move dev dependencies to regular dependencies
  templates/ts-playwright-test-runner/package.json
Labels: t-tooling
