Repository apify/actor-templates, pull requests merged in 2023-11, with the labels that each got.

#220 Scrapy: Returning a Request object in the Spider.parse works
  templates/python-scrapy/src/__main__.py
  templates/python-scrapy/src/apify/main.py
  templates/python-scrapy/src/apify/middlewares.py
  templates/python-scrapy/src/apify/scheduler.py
  templates/python-scrapy/src/apify/utils.py
  templates/python-scrapy/src/spiders/title.py
Labels: t-tooling

#223 feat: add wrapper templates
  dist/wrappers/python-scrapy.zip
  src/build.js
  src/build_templates.js
  src/consts.js
  src/index.js
  wrappers/manifest.json
  wrappers/python-scrapy/.actor/Dockerfile.template
  wrappers/python-scrapy/.actor/actor.template.json
  wrappers/python-scrapy/.actor/input_schema.template.json
  wrappers/python-scrapy/.dockerignore
  wrappers/python-scrapy/.gitignore
  wrappers/python-scrapy/requirements_apify.txt
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
  wrappers/python-scrapy/{projectFolder}/apify/main.template.py
  wrappers/python-scrapy/{projectFolder}/apify/middlewares.py
  wrappers/python-scrapy/{projectFolder}/apify/pipelines.py
  wrappers/python-scrapy/{projectFolder}/apify/scheduler.py
  wrappers/python-scrapy/{projectFolder}/apify/utils.py
Labels: t-tooling

#225 Scrapy-related utilities are moved to the Apify SDK
  templates/python-beautifulsoup/.gitignore
  templates/python-beautifulsoup/requirements.txt
  templates/python-empty/requirements.txt
  templates/python-playwright/.gitignore
  templates/python-playwright/requirements.txt
  templates/python-scrapy/.gitignore
  templates/python-scrapy/requirements.txt
  templates/python-scrapy/src/__main__.py
  templates/python-scrapy/src/apify/middlewares.py
  templates/python-scrapy/src/apify/pipelines.py
  templates/python-scrapy/src/apify/scheduler.py
  templates/python-scrapy/src/apify/utils.py
  templates/python-scrapy/src/main.py
  templates/python-selenium/.gitignore
  templates/python-selenium/requirements.txt
  templates/python-start/.gitignore
  templates/python-start/requirements.txt
  wrappers/python-scrapy/.gitignore
  wrappers/python-scrapy/requirements_apify.txt
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
  wrappers/python-scrapy/{projectFolder}/apify/middlewares.py
  wrappers/python-scrapy/{projectFolder}/apify/pipelines.py
  wrappers/python-scrapy/{projectFolder}/apify/scheduler.py
  wrappers/python-scrapy/{projectFolder}/apify/utils.py
  wrappers/python-scrapy/{projectFolder}/main.template.py
Labels: t-tooling

#226 skip checking of TS libs for now as crawlee 3.6 broke it with the got scraping upgrade
  README.md
  templates/ts-bootstrap-cheerio-crawler/tsconfig.json
  templates/ts-crawlee-cheerio/tsconfig.json
  templates/ts-crawlee-playwright-chrome/tsconfig.json
  templates/ts-crawlee-puppeteer-chrome/tsconfig.json
  templates/ts-empty/tsconfig.json
  templates/ts-playwright-test-runner/tsconfig.json
  templates/ts-start-bun/tsconfig.json
  templates/ts-start/tsconfig.json
Labels: adhoc, t-tooling

#231 fix: pin TS to 5.2 for now
  templates/ts-bootstrap-cheerio-crawler/package.json
  templates/ts-crawlee-cheerio/package.json
  templates/ts-crawlee-playwright-chrome/package.json
  templates/ts-crawlee-puppeteer-chrome/package.json
  templates/ts-empty/package.json
  templates/ts-playwright-test-runner/package.json
  templates/ts-start/package.json
Labels: adhoc, t-tooling

#234 Python Scrapy Actor: Improve logging configuration
  templates/python-scrapy/src/__main__.py
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
Labels: t-tooling

#233 Improve docs of the Apify Scrapy template (in wrappers)
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
  wrappers/python-scrapy/{projectFolder}/main.template.py
Labels: t-tooling

#236 Scrapy template: Minor code update and docs improvement
  templates/python-scrapy/src/__main__.py
  templates/python-scrapy/src/items.py
  templates/python-scrapy/src/main.py
  templates/python-scrapy/src/pipelines.py
  templates/python-scrapy/src/settings.py
  templates/python-scrapy/src/spiders/__init__.py
  templates/python-scrapy/src/spiders/title.py
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
  wrappers/python-scrapy/{projectFolder}/main.template.py
Labels: t-tooling

#238 Scrapy Actor: Update ActorDatasetPushPipeline from 1 to 1000
  templates/python-scrapy/src/main.py
  wrappers/python-scrapy/{projectFolder}/main.template.py
Labels: bug, adhoc, t-tooling

#239 Python templates: code finetuning, improve docs and comments
  templates/python-beautifulsoup/requirements.txt
  templates/python-beautifulsoup/src/__init__.py
  templates/python-beautifulsoup/src/__main__.py
  templates/python-beautifulsoup/src/main.py
  templates/python-empty/requirements.txt
  templates/python-empty/src/__main__.py
  templates/python-empty/src/main.py
  templates/python-playwright/requirements.txt
  templates/python-playwright/src/__init__.py
  templates/python-playwright/src/__main__.py
  templates/python-playwright/src/main.py
  templates/python-scrapy/requirements.txt
  templates/python-scrapy/src/__init__.py
  templates/python-selenium/requirements.txt
  templates/python-selenium/src/__init__.py
  templates/python-selenium/src/__main__.py
  templates/python-selenium/src/main.py
  templates/python-start/requirements.txt
  templates/python-start/src/__init__.py
  templates/python-start/src/__main__.py
  templates/python-start/src/main.py
Labels: t-tooling

#241 Python templates: Add code check step to the Dockerfiles
  templates/python-beautifulsoup/.actor/Dockerfile
  templates/python-empty/.actor/Dockerfile
  templates/python-playwright/.actor/Dockerfile
  templates/python-scrapy/.actor/Dockerfile
  templates/python-selenium/.actor/Dockerfile
  templates/python-start/.actor/Dockerfile
Labels: t-tooling

#242 Python Scrapy: Rm `max_depth` from default Actor input
  templates/python-scrapy/.actor/input_schema.json
  templates/python-scrapy/README.md
  templates/python-scrapy/src/main.py
  templates/python-scrapy/src/settings.py
Labels: t-tooling

#243 Scrapy Actor: Align changes between templates wrappers
  templates/python-scrapy/.dockerignore
  templates/python-scrapy/.gitignore
  wrappers/python-scrapy/.actor/Dockerfile.template
  wrappers/python-scrapy/.actor/input_schema.template.json
  wrappers/python-scrapy/.dockerignore
  wrappers/python-scrapy/.gitignore
  wrappers/python-scrapy/{projectFolder}/main.template.py
Labels: t-tooling

#244 Scrapy Actor: Add middlewares module
  templates/python-scrapy/src/middlewares.py
  templates/python-scrapy/src/settings.py
Labels: t-tooling

#246 Scrapy Actor: Set logging level of HTTPX to WARNING
  templates/python-scrapy/src/__main__.py
Labels: enhancement, adhoc, t-tooling
