Repository apify/actor-templates, pull requests merged in 2023-09, with the labels that each got.

#181 chore: Update Apify CLI installation instructions via Homebrew
  templates/console_readme_suffix.md
Labels: t-platform, adhoc

#200 fix: Fix `js-langchain` template, fix tests
  package-lock.json
  package.json
  templates/js-langchain/package.json
  test/templates.test.js
Labels: t-platform, adhoc, tested

#201 docs: add a comment to all the `main` files about ESM and import extensions
  templates/js-bootstrap-cheerio-crawler/src/main.js
  templates/js-crawlee-cheerio/src/main.js
  templates/js-crawlee-playwright-chrome/src/main.js
  templates/js-crawlee-puppeteer-chrome/src/main.js
  templates/js-cypress/src/main.js
  templates/js-empty/src/main.js
  templates/js-langchain/src/main.js
  templates/js-start/src/main.js
  templates/ts-bootstrap-cheerio-crawler/src/main.ts
  templates/ts-crawlee-cheerio/src/main.ts
  templates/ts-crawlee-playwright-chrome/src/main.ts
  templates/ts-crawlee-puppeteer-chrome/src/main.ts
  templates/ts-empty/src/main.ts
  templates/ts-start/src/main.ts
Labels: adhoc, t-tooling

#184 Python Scrapy Actor uses Request Queue
  templates/python-scrapy/requirements.txt
  templates/python-scrapy/src/main.py
  templates/python-scrapy/src/middlewares.py
  templates/python-scrapy/src/pipelines.py
  templates/python-scrapy/src/scheduler.py
  templates/python-scrapy/src/spiders/title_spider.py
  templates/python-scrapy/src/utils.py
Labels: t-tooling

#203 feat: Added bun-start template
  .github/workflows/build_archives.yaml
  dist/templates/ts-start-bun.zip
  templates/manifest.json
  templates/ts-start-bun/.actor/Dockerfile
  templates/ts-start-bun/.actor/actor.json
  templates/ts-start-bun/.actor/input_schema.json
  templates/ts-start-bun/.dockerignore
  templates/ts-start-bun/.gitignore
  templates/ts-start-bun/README.md
  templates/ts-start-bun/package.json
  templates/ts-start-bun/src/main.ts
  templates/ts-start-bun/tsconfig.json
  test/templates.test.js
Labels: adhoc, t-console, tested

#204 chore: fix ci for new playwright
  package-lock.json
  package.json
Labels: adhoc, t-tooling

#207 Update templates readmes
  templates/js-bootstrap-cheerio-crawler/README.md
  templates/js-crawlee-cheerio/README.md
  templates/js-crawlee-playwright-chrome/README.md
  templates/js-crawlee-puppeteer-chrome/README.md
  templates/js-cypress/README.md
  templates/js-empty/README.md
  templates/js-langchain/README.md
  templates/js-start/README.md
  templates/python-beautifulsoup/README.md
  templates/python-empty/README.md
  templates/python-playwright/README.md
  templates/python-scrapy/README.md
  templates/python-selenium/README.md
  templates/python-start/README.md
  templates/ts-bootstrap-cheerio-crawler/README.md
  templates/ts-crawlee-cheerio/README.md
  templates/ts-crawlee-playwright-chrome/README.md
  templates/ts-crawlee-puppeteer-chrome/README.md
  templates/ts-empty/README.md
  templates/ts-playwright-test-runner/README.md
  templates/ts-start-bun/README.md
  templates/ts-start/README.md
Labels: adhoc, t-web, product roadmap

#208 fix ts-node on node 20 + update all images to use node 18
  .github/workflows/lint_and_test.yaml
  templates/js-crawlee-cheerio/.actor/Dockerfile
  templates/js-crawlee-playwright-chrome/.actor/Dockerfile
  templates/js-crawlee-playwright-chrome/package.json
  templates/js-crawlee-puppeteer-chrome/.actor/Dockerfile
  templates/ts-bootstrap-cheerio-crawler/package.json
  templates/ts-crawlee-cheerio/.actor/Dockerfile
  templates/ts-crawlee-cheerio/package.json
  templates/ts-crawlee-playwright-chrome/.actor/Dockerfile
  templates/ts-crawlee-playwright-chrome/package.json
  templates/ts-crawlee-puppeteer-chrome/.actor/Dockerfile
  templates/ts-crawlee-puppeteer-chrome/package.json
  templates/ts-empty/package.json
  templates/ts-playwright-test-runner/.actor/Dockerfile
  templates/ts-playwright-test-runner/package.json
  templates/ts-start/package.json
Labels: adhoc, t-tooling
