Repository apify/actor-templates, pull requests merged in 2023-03, with the labels that each got.

#124 Added `meta.templateId` to `actor.json` and `input_schema` naming unification
  .gitignore
  dist/templates/js-crawlee-cheerio.zip
  dist/templates/js-crawlee-playwright-chrome.zip
  dist/templates/js-crawlee-puppeteer-chrome.zip
  dist/templates/js-empty.zip
  dist/templates/js-start.zip
  dist/templates/python-start-old.zip
  dist/templates/python-start.zip
  dist/templates/ts-crawlee-cheerio.zip
  dist/templates/ts-crawlee-playwright-chrome.zip
  dist/templates/ts-crawlee-puppeteer-chrome.zip
  dist/templates/ts-start.zip
  templates/js-crawlee-cheerio/.actor/actor.json
  templates/js-crawlee-playwright-chrome/.actor/actor.json
  templates/js-crawlee-puppeteer-chrome/.actor/actor.json
  templates/js-empty/.actor/actor.json
  templates/js-start/.actor/actor.json
  templates/js-start/.actor/input_schema.json
  templates/js-start/src/main.js
  templates/python-start-old/.actor/INPUT_SCHEMA.json
  templates/python-start-old/.actor/actor.json
  templates/python-start-old/src/main.py
  templates/python-start/.actor/INPUT_SCHEMA.json
  templates/python-start/.actor/actor.json
  templates/python-start/src/main.py
  templates/ts-crawlee-cheerio/.actor/actor.json
  templates/ts-crawlee-playwright-chrome/.actor/actor.json
  templates/ts-crawlee-puppeteer-chrome/.actor/actor.json
  templates/ts-start/.actor/INPUT_SCHEMA.json
  templates/ts-start/.actor/actor.json
  templates/ts-start/src/main.ts
  test/templates.test.js
Labels: t-web

#129 Fixed actor template naming `INPUT_SCHEMA` -> `input_schema` file naming
  templates/js-crawlee-cheerio/.actor/input_schema.json
  templates/js-crawlee-playwright-chrome/.actor/input_schema.json
  templates/js-crawlee-puppeteer-chrome/.actor/input_schema.json
  templates/js-empty/.actor/input_schema.json
  templates/python-start-old/.actor/input_schema.json
  templates/python-start/.actor/input_schema.json
  templates/ts-crawlee-cheerio/.actor/input_schema.json
  templates/ts-crawlee-playwright-chrome/.actor/input_schema.json
  templates/ts-crawlee-puppeteer-chrome/.actor/input_schema.json
  templates/ts-start/.actor/input_schema.json
Labels: bug, adhoc, t-web

#128 Feature: Add a Python + Scrapy template
  dist/templates/python-scrapy.zip
  templates/manifest.json
  templates/python-scrapy/.actor/Dockerfile
  templates/python-scrapy/.actor/README.md
  templates/python-scrapy/.actor/actor.json
  templates/python-scrapy/.actor/input_schema.json
  templates/python-scrapy/.dockerignore
  templates/python-scrapy/.editorconfig
  templates/python-scrapy/.gitignore
  templates/python-scrapy/requirements.txt
  templates/python-scrapy/scrapy.cfg
  templates/python-scrapy/src/__init__.py
  templates/python-scrapy/src/__main__.py
  templates/python-scrapy/src/items.py
  templates/python-scrapy/src/main.py
  templates/python-scrapy/src/pipelines.py
  templates/python-scrapy/src/settings.py
  templates/python-scrapy/src/spiders/__init__.py
  templates/python-scrapy/src/spiders/quotes_spider.py
Labels: t-platform, adhoc

#134 Graduate Python templates out of beta
  dist/templates/python-beautifulsoup.zip
  dist/templates/python-playwright.zip
  dist/templates/python-scrapy.zip
  dist/templates/python-selenium.zip
  dist/templates/python-start.zip
  templates/manifest.json
  templates/python-beautifulsoup/.actor/Dockerfile
  templates/python-beautifulsoup/requirements.txt
  templates/python-playwright/.actor/Dockerfile
  templates/python-playwright/requirements.txt
  templates/python-scrapy/.actor/Dockerfile
  templates/python-scrapy/requirements.txt
  templates/python-selenium/.actor/Dockerfile
  templates/python-selenium/requirements.txt
  templates/python-start/.actor/Dockerfile
  templates/python-start/requirements.txt
Labels: t-platform, adhoc

#113 Update `python-start` template to use the Python SDK
  dist/templates/python-start-old.zip
  templates/manifest.json
  templates/python-start-old/.actor/Dockerfile
  templates/python-start-old/.actor/README.md
  templates/python-start-old/.actor/actor.json
  templates/python-start-old/.actor/input_schema.json
  templates/python-start-old/.dockerignore
  templates/python-start-old/.editorconfig
  templates/python-start-old/.gitignore
  templates/python-start-old/requirements.txt
  templates/python-start-old/src/__init__.py
  templates/python-start-old/src/__main__.py
  templates/python-start-old/src/main.py
Labels: t-platform, adhoc

#132 Changed order of actor templates in `manifest.json` to start promoting python templates
  templates/manifest.json
Labels: adhoc, t-web

#135 Post-create messages for Python actors
  dist/templates/python-playwright.zip
  templates/manifest.json
  templates/python-playwright/src/main.py
Labels: t-platform, adhoc

#133 feat: add Playwright Test Runner template
  jest.config.js
  templates/manifest.json
  templates/ts-playwright-test-runner/.actor/Dockerfile
  templates/ts-playwright-test-runner/.actor/actor.json
  templates/ts-playwright-test-runner/.actor/input_schema.json
  templates/ts-playwright-test-runner/.actor/output_schema.json
  templates/ts-playwright-test-runner/.dockerignore
  templates/ts-playwright-test-runner/.eslintrc
  templates/ts-playwright-test-runner/.gitignore
  templates/ts-playwright-test-runner/README.md
  templates/ts-playwright-test-runner/package.json
  templates/ts-playwright-test-runner/playwright.config.ts
  templates/ts-playwright-test-runner/src/main.ts
  templates/ts-playwright-test-runner/src/runCodegen.ts
  templates/ts-playwright-test-runner/src/transform.ts
  templates/ts-playwright-test-runner/tests/first.spec.ts
  templates/ts-playwright-test-runner/tests/second.spec.ts
  templates/ts-playwright-test-runner/tsconfig.json
Labels: t-tooling

#130 feat: adding cypress template
  dist/templates/js-cypress.zip
  package-lock.json
  templates/js-cypress/.actor/Dockerfile
  templates/js-cypress/.actor/actor.json
  templates/js-cypress/.actor/input_schema.json
  templates/js-cypress/.actor/output_schema.json
  templates/js-cypress/.dockerignore
  templates/js-cypress/.editorconfig
  templates/js-cypress/.eslintrc
  templates/js-cypress/.gitignore
  templates/js-cypress/.nvmrc
  templates/js-cypress/README.md
  templates/js-cypress/cypress.config.js
  templates/js-cypress/cypress/e2e/first-spec.cy.js
  templates/js-cypress/cypress/e2e/second-spec.cy.js
  templates/js-cypress/cypress/support/e2e.js
  templates/js-cypress/main.js
  templates/js-cypress/package.json
  templates/manifest.json
Labels: t-console
