Repository apify/actor-templates, pull requests merged in 2023-10, with the labels that each got.

#211 fix: update Apify Python SDK to the latest version
  templates/python-beautifulsoup/requirements.txt
  templates/python-empty/requirements.txt
  templates/python-playwright/requirements.txt
  templates/python-selenium/requirements.txt
  templates/python-start/requirements.txt
Labels: t-tooling

#212 chore: add postinstall command for playwright templates
  templates/js-crawlee-playwright-chrome/package.json
  templates/ts-crawlee-playwright-chrome/package.json
  templates/ts-playwright-test-runner/package.json
Labels: adhoc, t-tooling

#199 Fix set logging level in Python Scrapy template
  templates/python-scrapy/requirements.txt
  templates/python-scrapy/src/__main__.py
Labels: t-tooling

#213 Format Python Actor templates
  templates/python-beautifulsoup/src/main.py
  templates/python-empty/src/main.py
  templates/python-playwright/src/main.py
  templates/python-scrapy/src/apify/main.py
  templates/python-scrapy/src/apify/middlewares.py
  templates/python-scrapy/src/apify/pipelines.py
  templates/python-scrapy/src/apify/scheduler.py
  templates/python-selenium/src/main.py
  templates/python-start/src/main.py
Labels: adhoc, t-tooling

#214 use latest playwright version again
  templates/js-crawlee-playwright-chrome/.actor/Dockerfile
  templates/js-crawlee-playwright-chrome/package.json
  templates/ts-crawlee-playwright-chrome/.actor/Dockerfile
  templates/ts-crawlee-playwright-chrome/package.json
Labels: adhoc, t-tooling

#215 Use HTTPX instead of Requests in Python templates
  templates/python-beautifulsoup/.actor/Dockerfile
  templates/python-beautifulsoup/README.md
  templates/python-beautifulsoup/requirements.txt
  templates/python-beautifulsoup/src/main.py
  templates/python-empty/.actor/Dockerfile
  templates/python-empty/README.md
  templates/python-empty/requirements.txt
  templates/python-empty/src/main.py
  templates/python-playwright/.actor/Dockerfile
  templates/python-playwright/README.md
  templates/python-scrapy/.actor/Dockerfile
  templates/python-scrapy/README.md
  templates/python-selenium/.actor/Dockerfile
  templates/python-selenium/README.md
  templates/python-start/.actor/Dockerfile
  templates/python-start/README.md
  templates/python-start/requirements.txt
  templates/python-start/src/main.py
Labels: t-tooling

#216 Fix deadlinks in the repository README
  README.md
Labels: bug, adhoc, t-tooling

#217 Replace Requests with HTTPX in the templates manifest
  templates/manifest.json
Labels: t-tooling

#221 Python Scrapy: improve doscstrings, add missing or fix broken typehints
  templates/python-scrapy/src/apify/main.py
  templates/python-scrapy/src/apify/pipelines.py
  templates/python-scrapy/src/items.py
  templates/python-scrapy/src/spiders/title.py
  templates/python-scrapy/src/spiders/title_spider.py
Labels: adhoc, t-tooling
