Repository apify/actor-templates, pull requests merged in 2023-07, with the labels that each got.

#166 fix: Minor copy and naming fixes for the new templates
  templates/js-start/README.md
  templates/manifest.json
Labels: bug, adhoc, t-web

#168 feat(js-cypress): readme update
  templates/js-cypress/README.md
  templates/js-cypress/cypress.config.js
  templates/js-cypress/package.json
  templates/js-cypress/src/main.js
Labels: t-web

#169 Selenium Readme
  templates/python-selenium/README.md
Labels: t-web

#173 fix: Specify the same Chrome and Chromedriver version in tests
  .github/workflows/lint_and_test.yaml
Labels: bug, t-platform, adhoc

#170 rewrite scrapy readme
  templates/manifest.json
  templates/python-scrapy/README.md
Labels: t-web
