Repository apify/actor-templates, pull requests merged in 2023-12, with the labels that each got.

#251 feat: reorder scrapy
  templates/manifest.json
Labels: t-web

#253 chore: move to tsx for templates from ts-node
  templates/ts-bootstrap-cheerio-crawler/package.json
  templates/ts-crawlee-cheerio/package.json
  templates/ts-crawlee-playwright-chrome/package.json
  templates/ts-crawlee-puppeteer-chrome/package.json
  templates/ts-empty/package.json
  templates/ts-playwright-test-runner/package.json
  templates/ts-start/package.json
  test/templates.test.js
Labels: adhoc, t-tooling, tested

#254 Scrapy Actor wrapper: Set logging level of HTTPX to WARNING
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
Labels: enhancement, adhoc, t-tooling

#258 Scrapy Actor: Fix duplicate log messages (p2)
  templates/python-scrapy/src/__main__.py
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
Labels: t-tooling
