Repository apify/actor-templates, pull requests merged in 2024-12, with the labels that each got.

#304 chore: Update Python templates to use SDK version 2.1
  templates/python-beautifulsoup/requirements.txt
  templates/python-crawlee-beautifulsoup/requirements.txt
  templates/python-crawlee-playwright/requirements.txt
  templates/python-empty/requirements.txt
  templates/python-playwright/requirements.txt
  templates/python-scrapy/requirements.txt
  templates/python-selenium/requirements.txt
  templates/python-standby/requirements.txt
  templates/python-start/requirements.txt
  wrappers/python-scrapy/requirements_apify.txt
Labels: adhoc, t-tooling

#306 chore: Enforce only major versions for Python projects
  templates/python-beautifulsoup/requirements.txt
  templates/python-crawlee-beautifulsoup/requirements.txt
  templates/python-crawlee-playwright/requirements.txt
  templates/python-empty/requirements.txt
  templates/python-playwright/requirements.txt
  templates/python-scrapy/requirements.txt
  templates/python-selenium/requirements.txt
  templates/python-standby/requirements.txt
  templates/python-start/requirements.txt
  wrappers/python-scrapy/requirements_apify.txt
Labels: t-tooling

#307 chore: bump `ts-playwright-test-runner` Playwright and Node version
  templates/js-crawlee-playwright-chrome/src/main.js
  templates/js-crawlee-puppeteer-chrome/src/main.js
  templates/python-crawlee-playwright/src/main.py
  templates/python-playwright/src/main.py
  templates/ts-crawlee-playwright-chrome/src/main.ts
  templates/ts-crawlee-puppeteer-chrome/src/main.ts
  templates/ts-playwright-test-runner/.actor/Dockerfile
  templates/ts-playwright-test-runner/.dockerignore
  templates/ts-playwright-test-runner/.gitignore
  templates/ts-playwright-test-runner/package.json
  templates/ts-playwright-test-runner/src/main.ts
  templates/ts-playwright-test-runner/tests/first.spec.ts
Labels: adhoc, t-tooling, tested
