Repository apify/actor-templates, pull requests merged in 2024-01, with the labels that each got.

#260 Add Scrapy `ApifyHttpProxyMiddleware` for managing proxies
  templates/python-beautifulsoup/requirements.txt
  templates/python-empty/requirements.txt
  templates/python-playwright/requirements.txt
  templates/python-scrapy/.actor/actor.json
  templates/python-scrapy/.actor/input_schema.json
  templates/python-scrapy/requirements.txt
  templates/python-scrapy/src/main.py
  templates/python-scrapy/src/middlewares.py
  templates/python-selenium/requirements.txt
  templates/python-start/requirements.txt
  wrappers/python-scrapy/.actor/actor.template.json
  wrappers/python-scrapy/.actor/input_schema.template.json
  wrappers/python-scrapy/requirements_apify.txt
  wrappers/python-scrapy/{projectFolder}/main.template.py
Labels: t-tooling

#262 Fixed init for `js-crawlee-playwright-chrome` and dynamic input fro `ts-crawlee-playwright-chrome` template
  templates/js-crawlee-playwright-chrome/src/main.js
  templates/ts-crawlee-playwright-chrome/.actor/input_schema.json
  templates/ts-crawlee-playwright-chrome/src/main.ts
Labels: bug, adhoc, t-web

#265 Scrapy Actor: Move `_get_scrapy_settings` to SDK
  templates/python-beautifulsoup/requirements.txt
  templates/python-empty/requirements.txt
  templates/python-playwright/requirements.txt
  templates/python-scrapy/requirements.txt
  templates/python-scrapy/src/main.py
  templates/python-selenium/requirements.txt
  templates/python-start/requirements.txt
  wrappers/python-scrapy/requirements_apify.txt
Labels: enhancement, adhoc, t-tooling

#269 Fix python templates: SDK == 1.5.3
  CONTRIBUTING.md
  templates/python-beautifulsoup/requirements.txt
  templates/python-empty/requirements.txt
  templates/python-playwright/requirements.txt
  templates/python-scrapy/requirements.txt
  templates/python-selenium/requirements.txt
  templates/python-start/requirements.txt
  test/templates.test.js
  wrappers/python-scrapy/requirements_apify.txt
Labels: bug, adhoc, t-tooling
