Repository apify/actor-templates, pull requests merged in 2024-09, with the labels that each got.

#279 ci: fix tests
  .github/workflows/lint_and_test.yaml
  .nvmrc
  package-lock.json
  src/consts.js
  templates/js-cypress/.nvmrc
  templates/manifest.json
  test/templates.test.js
Labels: adhoc, t-tooling, tested

#286 feat: log versions before installing npm dependencies
  templates/js-bootstrap-cheerio-crawler/.actor/Dockerfile
  templates/js-crawlee-cheerio/.actor/Dockerfile
  templates/js-crawlee-cheerio/src/main.js
  templates/js-crawlee-playwright-chrome/.actor/Dockerfile
  templates/js-crawlee-puppeteer-chrome/.actor/Dockerfile
  templates/js-empty/.actor/Dockerfile
  templates/js-langchain/.actor/Dockerfile
  templates/js-standby/.actor/Dockerfile
  templates/js-start/.actor/Dockerfile
  templates/ts-bootstrap-cheerio-crawler/.actor/Dockerfile
  templates/ts-crawlee-cheerio/.actor/Dockerfile
  templates/ts-crawlee-playwright-chrome/.actor/Dockerfile
  templates/ts-crawlee-puppeteer-chrome/.actor/Dockerfile
  templates/ts-empty/.actor/Dockerfile
  templates/ts-standby/.actor/Dockerfile
  templates/ts-start/.actor/Dockerfile
Labels: adhoc, t-tooling

#292 fix: Add 60 minutes timeout to template tests
  .github/workflows/lint_and_test.yaml
Labels: bug, t-platform, adhoc

#291 fix: Update js-langchain template
  README.md
  templates/js-langchain/.eslintrc
  templates/js-langchain/README.md
  templates/js-langchain/package.json
  templates/js-langchain/src/main.js
  templates/js-langchain/src/vector_index_cache.js
Labels: t-ai

#293 docs: update titles of python templates
  templates/manifest.json
  templates/python-beautifulsoup/README.md
  templates/python-crawlee-beautifulsoup/README.md
  templates/python-crawlee-playwright/README.md
  templates/python-empty/README.md
  templates/python-playwright/README.md
  templates/python-scrapy/README.md
  templates/python-selenium/README.md
  templates/python-standby/README.md
Labels: adhoc, t-tooling
