Repository apify/actor-templates, pull requests merged in 2024-08, with the labels that each got.

#284 fix: update TS template comments to reflect correct TS file extension
  templates/ts-crawlee-puppeteer-chrome/README.md
  templates/ts-crawlee-puppeteer-chrome/src/main.ts
Labels: documentation, adhoc, content

#283 fix: incorrect input_schema.json titles
  templates/js-crawlee-puppeteer-chrome/.actor/input_schema.json
  templates/ts-crawlee-puppeteer-chrome/.actor/input_schema.json
Labels: documentation, adhoc, t-console, content

#282 Update ts-start-bun template prefill url property
  templates/ts-start-bun/.actor/input_schema.json
Labels: bug, adhoc, t-console
