Repository apify/actor-templates, pull requests merged in 2025-02, with the labels that each got.

#316 chore: add static analysis for Python templates
  .github/workflows/lint_and_test.yaml
  .gitignore
  Makefile
  poetry.lock
  pyproject.toml
  templates/python-beautifulsoup/src/__init__.py
  templates/python-beautifulsoup/src/main.py
  templates/python-beautifulsoup/src/py.typed
  templates/python-crawlee-beautifulsoup/src/__init__.py
  templates/python-crawlee-beautifulsoup/src/main.py
  templates/python-crawlee-beautifulsoup/src/py.typed
  templates/python-crawlee-playwright/src/__init__.py
  templates/python-crawlee-playwright/src/main.py
  templates/python-crawlee-playwright/src/py.typed
  templates/python-empty/src/__init__.py
  templates/python-empty/src/py.typed
  templates/python-playwright/src/__init__.py
  templates/python-playwright/src/main.py
  templates/python-playwright/src/py.typed
  templates/python-scrapy/src/__init__.py
  templates/python-scrapy/src/__main__.py
  templates/python-scrapy/src/main.py
  templates/python-scrapy/src/middlewares.py
  templates/python-scrapy/src/pipelines.py
  templates/python-scrapy/src/spiders/title.py
  templates/python-selenium/src/__init__.py
  templates/python-selenium/src/main.py
  templates/python-selenium/src/py.typed
  templates/python-standby/src/__init__.py
  templates/python-standby/src/main.py
  templates/python-standby/src/py.typed
  templates/python-start/src/__init__.py
  templates/python-start/src/main.py
  templates/python-start/src/py.typed
Labels: adhoc, infrastructure, t-tooling

#312 feat: python-langchain template
  templates/manifest.json
  templates/python-langgraph/.actor/Dockerfile
  templates/python-langgraph/.actor/actor.json
  templates/python-langgraph/.actor/dataset_schema.json
  templates/python-langgraph/.actor/input_schema.json
  templates/python-langgraph/.dockerignore
  templates/python-langgraph/.gitignore
  templates/python-langgraph/README.md
  templates/python-langgraph/requirements.txt
  templates/python-langgraph/src/__init__.py
  templates/python-langgraph/src/__main__.py
  templates/python-langgraph/src/main.py
  templates/python-langgraph/src/models.py
  templates/python-langgraph/src/tools.py
  templates/python-langgraph/src/utils.py
Labels: t-ai

#321 chore: update Python templates to use 3.13 & fix Scrapy on Windows
  .github/workflows/lint_and_test.yaml
  templates/python-beautifulsoup/.actor/Dockerfile
  templates/python-crawlee-beautifulsoup/.actor/Dockerfile
  templates/python-crawlee-playwright/.actor/Dockerfile
  templates/python-empty/.actor/Dockerfile
  templates/python-playwright/.actor/Dockerfile
  templates/python-scrapy/.actor/Dockerfile
  templates/python-scrapy/.actor/input_schema.json
  templates/python-scrapy/src/__main__.py
  templates/python-scrapy/src/spiders/title.py
  templates/python-selenium/.actor/Dockerfile
  templates/python-standby/.actor/Dockerfile
  templates/python-start/.actor/Dockerfile
  wrappers/python-scrapy/.actor/Dockerfile.template
  wrappers/python-scrapy/.actor/input_schema.template.json
  wrappers/python-scrapy/requirements_apify.txt
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
  wrappers/python-scrapy/{projectFolder}/main.template.py
Labels: adhoc, t-tooling

#322 fix: python-langgraph template ppe
  templates/python-langgraph/.actor/input_schema.json
  templates/python-langgraph/.actor/pay_per_event.json
  templates/python-langgraph/src/main.py
  templates/python-langgraph/src/ppe_utils.py
Labels: t-ai

#318 feat: add LangGraph.js Agent into templates
  templates/js-langgraph-agent/.actor/Dockerfile
  templates/js-langgraph-agent/.actor/actor.json
  templates/js-langgraph-agent/.actor/input_schema.json
  templates/js-langgraph-agent/.actor/pay_per_event.json
  templates/js-langgraph-agent/.dockerignore
  templates/js-langgraph-agent/.eslintrc
  templates/js-langgraph-agent/.gitignore
  templates/js-langgraph-agent/README.md
  templates/js-langgraph-agent/package.json
  templates/js-langgraph-agent/src/main.js
  templates/js-langgraph-agent/src/tools.js
  templates/manifest.json
  templates/python-llamaindex-agent/.actor/actor.json
Labels: t-ai

#324 feat: add llama index ppe
  templates/python-llamaindex-agent/.actor/input_schema.json
  templates/python-llamaindex-agent/.actor/pay_per_event.json
  templates/python-llamaindex-agent/README.md
  templates/python-llamaindex-agent/requirements.txt
  templates/python-llamaindex-agent/src/main.py
  templates/python-llamaindex-agent/src/tools.py
Labels: t-ai

#319 feat: python-crewai template
  templates/manifest.json
  templates/python-crewai/.actor/Dockerfile
  templates/python-crewai/.actor/actor.json
  templates/python-crewai/.actor/dataset_schema.json
  templates/python-crewai/.actor/input_schema.json
  templates/python-crewai/.actor/pay_per_event.json
  templates/python-crewai/.dockerignore
  templates/python-crewai/.gitignore
  templates/python-crewai/README.md
  templates/python-crewai/requirements.txt
  templates/python-crewai/src/__init__.py
  templates/python-crewai/src/__main__.py
  templates/python-crewai/src/main.py
  templates/python-crewai/src/models.py
  templates/python-crewai/src/ppe_utils.py
  templates/python-crewai/src/tools.py
Labels: t-ai

#314 feat: ts-bee-agent template
  package-lock.json
  package.json
  templates/manifest.json
  templates/ts-bee-agent/.actor/Dockerfile
  templates/ts-bee-agent/.actor/actor.json
  templates/ts-bee-agent/.actor/dataset_schema.json
  templates/ts-bee-agent/.actor/input_schema.json
  templates/ts-bee-agent/.actor/pay_per_event.json
  templates/ts-bee-agent/.dockerignore
  templates/ts-bee-agent/.editorconfig
  templates/ts-bee-agent/.eslintrc
  templates/ts-bee-agent/.gitignore
  templates/ts-bee-agent/README.md
  templates/ts-bee-agent/package.json
  templates/ts-bee-agent/src/main.ts
  templates/ts-bee-agent/src/ppe_events.ts
  templates/ts-bee-agent/src/ppe_utils.ts
  templates/ts-bee-agent/src/structured_response_generator.ts
  templates/ts-bee-agent/src/tools/calculator.ts
  templates/ts-bee-agent/src/tools/instagram.ts
  templates/ts-bee-agent/tsconfig.json
Labels: t-ai

#326 chore: rm nest-asyncio from pyproject.toml
  pyproject.toml
  uv.lock
Labels: adhoc, t-tooling

#327 fix: add package-lock.json back
  package-lock.json
Labels: t-ai

#329 fix: ts-bee-agent template
  templates/ts-bee-agent/.actor/input_schema.json
  templates/ts-bee-agent/src/main.ts
  templates/ts-bee-agent/src/tools/instagram.ts
Labels: t-ai

#328 fix: python-crewai template
  templates/js-crawlee-puppeteer-chrome/src/main.js
  templates/python-crewai/.actor/input_schema.json
  templates/python-crewai/README.md
  templates/python-crewai/src/main.py
  templates/python-crewai/src/tools.py
  templates/ts-crawlee-puppeteer-chrome/src/main.ts
  test/templates.test.js
Labels: tested, t-ai

#336 feat: add Camoufox-based Crawlee JS/TS templates
  templates/js-crawlee-playwright-camoufox/.actor/Dockerfile
  templates/js-crawlee-playwright-camoufox/.actor/actor.json
  templates/js-crawlee-playwright-camoufox/.actor/input_schema.json
  templates/js-crawlee-playwright-camoufox/.dockerignore
  templates/js-crawlee-playwright-camoufox/.editorconfig
  templates/js-crawlee-playwright-camoufox/.eslintrc
  templates/js-crawlee-playwright-camoufox/.gitignore
  templates/js-crawlee-playwright-camoufox/README.md
  templates/js-crawlee-playwright-camoufox/package.json
  templates/js-crawlee-playwright-camoufox/src/main.js
  templates/js-crawlee-playwright-camoufox/src/routes.js
  templates/manifest.json
  templates/ts-crawlee-playwright-camoufox/.actor/Dockerfile
  templates/ts-crawlee-playwright-camoufox/.actor/actor.json
  templates/ts-crawlee-playwright-camoufox/.actor/input_schema.json
  templates/ts-crawlee-playwright-camoufox/.dockerignore
  templates/ts-crawlee-playwright-camoufox/.editorconfig
  templates/ts-crawlee-playwright-camoufox/.eslintrc
  templates/ts-crawlee-playwright-camoufox/.gitignore
  templates/ts-crawlee-playwright-camoufox/README.md
  templates/ts-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-camoufox/src/main.ts
  templates/ts-crawlee-playwright-camoufox/src/routes.ts
  templates/ts-crawlee-playwright-camoufox/tsconfig.json
Labels: adhoc, t-tooling

#337 fix: install `Camoufox` browsers in TS Camoufox template
  templates/ts-crawlee-playwright-camoufox/package.json
Labels: adhoc, t-tooling

#332 fix: docker non root
  .github/workflows/test_dockerfile_builds.yml
  scripts/test_docker_builds.sh
  templates/js-bootstrap-cheerio-crawler/.actor/Dockerfile
  templates/js-crawlee-cheerio/.actor/Dockerfile
  templates/js-crawlee-puppeteer-chrome/.actor/Dockerfile
  templates/js-cypress/.actor/Dockerfile
  templates/js-empty/.actor/Dockerfile
  templates/js-langchain/.actor/Dockerfile
  templates/js-langgraph-agent/.actor/Dockerfile
  templates/js-langgraph-agent/.actor/input_schema.json
  templates/js-standby/.actor/Dockerfile
  templates/js-standby/src/main.js
  templates/js-start/.actor/Dockerfile
  templates/manifest.json
  templates/python-beautifulsoup/.actor/Dockerfile
  templates/python-crawlee-beautifulsoup/.actor/Dockerfile
  templates/python-crewai/.actor/Dockerfile
  templates/python-crewai/.actor/input_schema.json
  templates/python-crewai/src/models.py
  templates/python-empty/.actor/Dockerfile
  templates/python-langgraph/.actor/Dockerfile
  templates/python-langgraph/.actor/input_schema.json
  templates/python-langgraph/src/main.py
  templates/python-llamaindex-agent/.actor/Dockerfile
  templates/python-llamaindex-agent/.actor/input_schema.json
  templates/python-scrapy/.actor/Dockerfile
  templates/python-standby/.actor/Dockerfile
  templates/python-standby/src/main.py
  templates/python-start/.actor/Dockerfile
  templates/ts-bee-agent/.actor/Dockerfile
  templates/ts-bee-agent/.actor/input_schema.json
  templates/ts-bootstrap-cheerio-crawler/.actor/Dockerfile
  templates/ts-crawlee-cheerio/.actor/Dockerfile
  templates/ts-empty/.actor/Dockerfile
  templates/ts-standby/.actor/Dockerfile
  templates/ts-standby/src/main.ts
  templates/ts-start-bun/.actor/Dockerfile
  templates/ts-start/.actor/Dockerfile
Labels: tested, t-ai

#338 fix: do not skip `camoufox` install in Docker build
  templates/js-crawlee-playwright-camoufox/.actor/Dockerfile
  templates/js-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-camoufox/.actor/Dockerfile
  templates/ts-crawlee-playwright-camoufox/package.json
Labels: adhoc, t-tooling
