Repository apify/actor-templates, pull requests merged in 2025-06, with the labels that each got.

#399 feat: use Camoufox base Docker images
  templates/js-crawlee-playwright-camoufox/Dockerfile
  templates/js-crawlee-playwright-camoufox/package.json
  templates/js-crawlee-playwright-camoufox/src/main.js
  templates/ts-crawlee-playwright-camoufox/Dockerfile
  templates/ts-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-camoufox/src/main.ts
Labels: adhoc, t-tooling

#413 ci: enable renovate
  renovate.json
Labels: adhoc, t-tooling

#422 chore: update some JS/TS templates dependencies
  templates/js-bootstrap-cheerio-crawler/package.json
  templates/js-crawlee-cheerio/package.json
  templates/js-crawlee-playwright-camoufox/Dockerfile
  templates/js-crawlee-playwright-camoufox/package.json
  templates/js-crawlee-playwright-chrome/Dockerfile
  templates/js-crawlee-playwright-chrome/package.json
  templates/js-crawlee-puppeteer-chrome/package.json
  templates/js-cypress/package.json
  templates/js-empty/package.json
  templates/js-langchain/package.json
  templates/js-langgraph-agent/package.json
  templates/js-standby/package.json
  templates/js-start/package.json
  templates/ts-beeai-agent/package.json
  templates/ts-bootstrap-cheerio-crawler/package.json
  templates/ts-crawlee-cheerio/package.json
  templates/ts-crawlee-playwright-camoufox/Dockerfile
  templates/ts-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-chrome/Dockerfile
  templates/ts-crawlee-playwright-chrome/package.json
  templates/ts-crawlee-puppeteer-chrome/package.json
  templates/ts-empty/package.json
  templates/ts-mastraai/package.json
  templates/ts-mcp-server/package.json
  templates/ts-playwright-test-runner/Dockerfile
  templates/ts-playwright-test-runner/package.json
  templates/ts-standby/package.json
  templates/ts-start-bun/package.json
  templates/ts-start/package.json
Labels: adhoc, t-tooling

#434 fix: use `import.meta.dirname`
  renovate.json
  templates/manifest.json
  templates/python-mcp-server/.actor/actor.json
  templates/python-mcp-server/README.md
  templates/ts-mcp-server/.actor/actor.json
  templates/ts-mcp-server/README.md
  templates/ts-mcp-server/package.json
  templates/ts-mcp-server/src/lib/getVersion.ts
  templates/ts-playwright-test-runner/src/main.ts
  templates/ts-playwright-test-runner/src/runCodegen.ts
Labels: adhoc, t-tooling

#446 fix: Correct the type for `startUrls` input in TypeScript templates
  templates/ts-crawlee-cheerio/src/main.ts
  templates/ts-crawlee-playwright-camoufox/src/main.ts
  templates/ts-crawlee-playwright-chrome/src/main.ts
  templates/ts-crawlee-puppeteer-chrome/src/main.ts
Labels: t-core-services, adhoc

#448 fix: change ts-mcp-template server to @modelcontextprotocol/server-everything
  templates/ts-mcp-server/README.md
  templates/ts-mcp-server/package.json
  templates/ts-mcp-server/src/main.ts
Labels: t-ai

#449 fix: puppeteer templates that failed on README.md npm run format and ignore venv/.venv and node_modules in eslint config
  eslint.config.mjs
  templates/js-crawlee-puppeteer-chrome/README.md
  templates/ts-crawlee-puppeteer-chrome/README.md
Labels: t-ai

#453 chore: bump puppeteer
  package-lock.json
  package.json
  templates/js-crawlee-puppeteer-chrome/Dockerfile
  templates/js-crawlee-puppeteer-chrome/package.json
  templates/ts-crawlee-puppeteer-chrome/Dockerfile
  templates/ts-crawlee-puppeteer-chrome/package.json
Labels: adhoc, t-tooling

#457 chore: fix formatting
  templates/console_readme_suffix.md
  templates/js-crawlee-puppeteer-chrome/README.md
  templates/ts-crawlee-puppeteer-chrome/README.md
Labels: adhoc, t-tooling
