Repository apify/actor-templates, pull requests merged in 2025-05, with the labels that each got.

#398 feat: add ts actorized mcp server stdio template
  templates/manifest.json
  templates/ts-mcp-server/.actor/Dockerfile
  templates/ts-mcp-server/.actor/actor.json
  templates/ts-mcp-server/.actor/pay_per_event.json
  templates/ts-mcp-server/.dockerignore
  templates/ts-mcp-server/.editorconfig
  templates/ts-mcp-server/.eslintrc
  templates/ts-mcp-server/.gitignore
  templates/ts-mcp-server/README.md
  templates/ts-mcp-server/package.json
  templates/ts-mcp-server/src/billing.ts
  templates/ts-mcp-server/src/lib/getLogger.ts
  templates/ts-mcp-server/src/lib/getVersion.ts
  templates/ts-mcp-server/src/lib/onSignals.ts
  templates/ts-mcp-server/src/lib/server.ts
  templates/ts-mcp-server/src/lib/types.ts
  templates/ts-mcp-server/src/main.ts
  templates/ts-mcp-server/tsconfig.json
Labels: t-ai

#403 fix(ts-mcp-server): switch to sequential npm mcp server processing
  templates/ts-mcp-server/.actor/Dockerfile
  templates/ts-mcp-server/.actor/actor.json
  templates/ts-mcp-server/README.md
  templates/ts-mcp-server/package.json
  templates/ts-mcp-server/src/main.ts
Labels: t-ai

#406 fix: `actor` -> `Actor`
  CONTRIBUTING.md
  README.md
  templates/js-bootstrap-cheerio-crawler/package.json
  templates/js-crawlee-cheerio/package.json
  templates/js-crawlee-playwright-camoufox/README.md
  templates/js-crawlee-playwright-camoufox/package.json
  templates/js-crawlee-playwright-chrome/README.md
  templates/js-crawlee-playwright-chrome/package.json
  templates/js-crawlee-puppeteer-chrome/package.json
  templates/js-cypress/.actor/input_schema.json
  templates/js-cypress/cypress/e2e/second-spec.cy.js
  templates/js-empty/package.json
  templates/js-langchain/README.md
  templates/js-langchain/package.json
  templates/js-langchain/src/main.js
  templates/js-langgraph-agent/package.json
  templates/js-standby/package.json
  templates/js-start/package.json
  templates/local_readme_suffix.md
  templates/python-playwright/src/main.py
  templates/python-selenium/src/main.py
  templates/ts-bootstrap-cheerio-crawler/package.json
  templates/ts-crawlee-cheerio/package.json
  templates/ts-crawlee-playwright-camoufox/README.md
  templates/ts-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-chrome/README.md
  templates/ts-crawlee-playwright-chrome/package.json
  templates/ts-crawlee-puppeteer-chrome/package.json
  templates/ts-empty/package.json
  templates/ts-mastraai/src/tools.ts
  templates/ts-mcp-server/package.json
  templates/ts-playwright-test-runner/.actor/input_schema.json
  templates/ts-standby/package.json
  templates/ts-start/package.json
Labels: adhoc, t-infra

#407 pin playwright and puppeteer versions in package.json and dockerfile
  templates/js-crawlee-playwright-camoufox/Dockerfile
  templates/js-crawlee-playwright-camoufox/package.json
  templates/js-crawlee-playwright-chrome/Dockerfile
  templates/js-crawlee-playwright-chrome/package.json
  templates/js-crawlee-puppeteer-chrome/Dockerfile
  templates/js-crawlee-puppeteer-chrome/package.json
  templates/ts-crawlee-playwright-camoufox/Dockerfile
  templates/ts-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-chrome/Dockerfile
  templates/ts-crawlee-playwright-chrome/package.json
  templates/ts-crawlee-puppeteer-chrome/Dockerfile
  templates/ts-crawlee-puppeteer-chrome/package.json
  templates/ts-playwright-test-runner/Dockerfile
Labels: adhoc, t-tooling
