Repository apify/actor-templates, pull requests merged in 2025-04, with the labels that each got.

#367 feat: add AI use case to manifest
  templates/manifest.json
Labels: t-web

#370 chore: Run tests on fork based PRs
  .github/workflows/lint_and_test.yaml
Labels: adhoc, debt, t-tooling

#374 Revert "chore: Run tests on fork based PRs"
  .github/workflows/lint_and_test.yaml
Labels: adhoc, t-tooling

#390 fix: use apify.com consistently as the startUrls/globs
  templates/js-crawlee-cheerio/src/main.js
  templates/js-crawlee-playwright-camoufox/src/main.js
  templates/js-crawlee-playwright-chrome/src/main.js
  templates/ts-crawlee-cheerio/.actor/input_schema.json
  templates/ts-crawlee-cheerio/src/main.ts
  templates/ts-crawlee-playwright-camoufox/.actor/input_schema.json
  templates/ts-crawlee-playwright-camoufox/src/main.ts
  templates/ts-crawlee-playwright-chrome/.actor/input_schema.json
  templates/ts-crawlee-playwright-chrome/src/main.ts
  templates/ts-crawlee-puppeteer-chrome/src/main.ts
Labels: adhoc, t-tooling

#391 Update pydanticai example to lastest release of the package
  pyproject.toml
  templates/python-pydanticai/requirements.txt
  templates/python-pydanticai/src/agents.py
  templates/python-pydanticai/src/main.py
  uv.lock
Labels: adhoc, t-tooling

#394 fix: remove stray "main" field in the `ts-playwright-test-runner` test
  templates/ts-playwright-test-runner/package.json
Labels: adhoc, t-tooling

#393 chore: bump Camoufox version
  templates/js-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-camoufox/package.json
Labels: adhoc, t-tooling
