Repository apify/actor-templates, pull requests merged in 2025-03, with the labels that each got.

#335 chore: Add icons (technologies) for AI Agent templates
  README.md
  templates/manifest.json
Labels: t-ai

#339 fix: update crewai template
  templates/python-crewai/.actor/dataset_schema.json
  templates/python-crewai/.actor/input_schema.json
  templates/python-crewai/.actor/pay_per_event.json
  templates/python-crewai/README.md
  templates/python-crewai/src/main.py
  templates/python-crewai/src/models.py
  templates/python-crewai/src/ppe_utils.py
  templates/python-crewai/src/tools.py
Labels: t-ai

#341 fix: crewai actor start gb -> actor start ppe event
  templates/python-crewai/.actor/pay_per_event.json
  templates/python-crewai/README.md
  templates/python-crewai/src/main.py
  templates/python-crewai/src/ppe_utils.py
Labels: t-ai

#342 fix: python-crawlee-playwright add no sandbox
  templates/python-crawlee-playwright/src/main.py
Labels: t-ai

#345 fix: pin playwright to 1.50.1 in camoufox templates
  templates/js-crawlee-playwright-camoufox/.actor/Dockerfile
  templates/js-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-camoufox/.actor/Dockerfile
  templates/ts-crawlee-playwright-camoufox/package.json
Labels: adhoc, t-tooling

#343 fix: unify agent ppe events
  templates/js-langgraph-agent/.actor/pay_per_event.json
  templates/js-langgraph-agent/src/main.js
  templates/python-crewai/.actor/pay_per_event.json
  templates/python-langgraph/.actor/pay_per_event.json
  templates/python-langgraph/src/main.py
  templates/python-langgraph/src/ppe_utils.py
  templates/python-llamaindex-agent/.actor/pay_per_event.json
  templates/python-llamaindex-agent/src/main.py
  templates/ts-bee-agent/.actor/pay_per_event.json
  templates/ts-bee-agent/src/main.ts
  templates/ts-bee-agent/src/ppe_events.ts
  templates/ts-bee-agent/src/ppe_utils.ts
Labels: t-ai

#346 feat: Add ubi, the universal binary installer, to cli template
  templates/cli-start/.actor/Dockerfile
Labels: adhoc, t-tooling

#355 chore(deps): update root-level pyproject deps
  pyproject.toml
  uv.lock
Labels: adhoc, t-tooling

#356 fix: unpin playwright in camoufox templates
  package-lock.json
  package.json
  templates/js-crawlee-playwright-camoufox/.actor/Dockerfile
  templates/js-crawlee-playwright-camoufox/package.json
  templates/ts-crawlee-playwright-camoufox/.actor/Dockerfile
  templates/ts-crawlee-playwright-camoufox/package.json
Labels: adhoc, t-tooling

#357 ci: Add Python type checks
  .github/workflows/lint_and_test.yaml
  Makefile
  pyproject.toml
  templates/python-beautifulsoup/src/main.py
  templates/python-crawlee-beautifulsoup/src/main.py
  templates/python-crawlee-playwright/src/main.py
  templates/python-crewai/src/main.py
  templates/python-crewai/src/models.py
  templates/python-crewai/src/tools.py
  templates/python-empty/src/main.py
  templates/python-langgraph/src/main.py
  templates/python-langgraph/src/models.py
  templates/python-langgraph/src/tools.py
  templates/python-langgraph/src/utils.py
  templates/python-llamaindex-agent/src/agent.py
  templates/python-llamaindex-agent/src/main.py
  templates/python-playwright/src/main.py
  templates/python-scrapy/src/items.py
  templates/python-scrapy/src/main.py
  templates/python-scrapy/src/middlewares.py
  templates/python-scrapy/src/pipelines.py
  templates/python-scrapy/src/spiders/title.py
  templates/python-selenium/src/main.py
  templates/python-standby/src/main.py
  templates/python-start/src/main.py
  uv.lock
  wrappers/python-scrapy/{projectFolder}/__main__.template.py
  wrappers/python-scrapy/{projectFolder}/main.template.py
Labels: infrastructure, t-tooling

#359 fix: make camoufox template names unique
  templates/manifest.json
Labels: adhoc, t-console

#360 feat: Add PydanticAI template
  templates/manifest.json
  templates/python-pydanticai/.actor/Dockerfile
  templates/python-pydanticai/.actor/actor.json
  templates/python-pydanticai/.actor/input_schema.json
  templates/python-pydanticai/.actor/pay_per_event.json
  templates/python-pydanticai/.dockerignore
  templates/python-pydanticai/.gitignore
  templates/python-pydanticai/README.md
  templates/python-pydanticai/requirements.txt
  templates/python-pydanticai/src/__init__.py
  templates/python-pydanticai/src/__main__.py
  templates/python-pydanticai/src/agents.py
  templates/python-pydanticai/src/main.py
  templates/python-pydanticai/src/py.typed
Labels: adhoc, t-tooling

#362 fix: Fix docker build of Python Crawlee templates
  templates/python-beautifulsoup/.actor/Dockerfile
  templates/python-crawlee-beautifulsoup/.actor/Dockerfile
  templates/python-crawlee-playwright/.actor/Dockerfile
  templates/python-crewai/.actor/Dockerfile
  templates/python-empty/.actor/Dockerfile
  templates/python-langgraph/.actor/Dockerfile
  templates/python-llamaindex-agent/.actor/Dockerfile
  templates/python-playwright/.actor/Dockerfile
  templates/python-scrapy/.actor/Dockerfile
  templates/python-selenium/.actor/Dockerfile
  templates/python-standby/.actor/Dockerfile
  templates/python-start/.actor/Dockerfile
  wrappers/python-scrapy/.actor/Dockerfile.template
Labels: bug, adhoc, t-tooling
